
const units=[
 {num:'810 NAS',base:'HMS Ark Royal / Hal Far',theatre:'Mediterranean',impact:92,marks:'Mk.I',codes:'A2, A4, carrier deck letters',crew:'Mediterranean carrier crews',pilot:'Taranto and Malta strike crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=810%20Naval%20Air%20Squadron%20Swordfish',ops:'Mediterranean carrier strike unit covering reconnaissance, torpedo attack and convoy support. Good subject for early-war shadow shading, torpedo fit, worn fabric, salt bleaching and deck-handling scuffs.',notes:'Taranto-era finish, torpedo loading, carrier deck wear, Mediterranean fading',map:'taranto'},
 {num:'815 NAS',base:'HMS Illustrious / Dekheila',theatre:'Mediterranean',impact:98,marks:'Mk.I',codes:'5A, 5B, 5H style carrier codes',crew:'Taranto raid crews',pilot:'Lt Cdr K. Williamson and Taranto crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=815%20Naval%20Air%20Squadron%20Swordfish',ops:'The definitive Taranto modelling subject. Slow Swordfish attacked the Italian fleet anchorage at night, so black distemper undersides, torpedo gear, fabric texture and carrier grime matter more than clean display finishes.',notes:'Taranto raid, night torpedo attack, black distemper, aircraft 5A/5B style codes',map:'taranto'},
 {num:'816 NAS',base:'MAC ships / escort carriers',theatre:'Atlantic',impact:74,marks:'Mk.II / Mk.III',codes:'Escort-carrier letters; ASV/radar fit varies',crew:'Atlantic convoy crews',pilot:'ASW patrol crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1138.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=816%20Naval%20Air%20Squadron%20Swordfish',ops:'Atlantic convoy and anti-submarine Swordfish operations. Model dull finishes, depth charges, rocket rails or ASV aerials depending on date and ship.',notes:'convoy escort, ASW stores, salt fading, late-war finish',map:'atlantic'},
 {num:'818 NAS',base:'HMS Ark Royal',theatre:'Atlantic',impact:95,marks:'Mk.I',codes:'5C / L9726 association, Ark Royal letters',crew:'Bismarck strike crews',pilot:'Sub Lt John “Jock” Moffat and Ark Royal crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900',photoLink:'https://navywings.org.uk/portfolio/lt-cdr-jock-moffat/',ops:'Bismarck strike unit. Ark Royal Swordfish attacked in dreadful weather and helped disable Bismarck’s steering. Model the aircraft wet, salt-marked, heavily handled and not pristine.',notes:'Bismarck strike, Atlantic weather, Ark Royal deck handling, torpedo fit',map:'arkroyal'},
 {num:'819 NAS',base:'Hatston / Arctic routes',theatre:'Training / Arctic',impact:68,marks:'Mk.II / Mk.III',codes:'Arctic convoy and training codes',crew:'Arctic convoy crews',pilot:'North Atlantic crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Fairey%20Swordfish%20Cockpit.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=819%20Naval%20Air%20Squadron%20Swordfish',ops:'Useful for cold-weather and late-service Swordfish subjects. Focus on dull paint, ice, salt, soot, rocket rails and battered fabric.',notes:'Arctic convoy, cold weather, rocket rails, worn fabric',map:'arctic'},
 {num:'820 NAS',base:'HMS Ark Royal / HMS Victorious',theatre:'Atlantic',impact:88,marks:'Mk.I / Mk.II',codes:'Fleet carrier deck letters',crew:'Atlantic carrier crews',pilot:'Ark Royal and Victorious crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=820%20Naval%20Air%20Squadron%20Swordfish',ops:'A strong Atlantic Fleet carrier subject with reconnaissance and torpedo strike work. Useful for mixed early-war FAA finishes, carrier codes, rigging and weathered fabric.',notes:'Atlantic carrier operations, torpedo strike, early FAA markings',map:'arkroyal'},
 {num:'821 NAS',base:'HMS Courageous / early-war carriers',theatre:'Home Fleet',impact:70,marks:'Mk.I',codes:'Pre-war / early-war carrier codes',crew:'Early-war FAA crews',pilot:'Home Fleet crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1138.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=821%20Naval%20Air%20Squadron%20Swordfish',ops:'Early-war Home Fleet Swordfish subject. Good for pre-war/early-war markings, cleaner fabric finish, and early reconnaissance/torpedo bomber roles.',notes:'Home Fleet, early-war finish, biplane rigging, carrier codes',map:'homefleet'},
 {num:'824 NAS',base:'HMS Eagle / Mediterranean',theatre:'Mediterranean',impact:80,marks:'Mk.I / Mk.II',codes:'Mediterranean carrier codes',crew:'Mediterranean strike crews',pilot:'HMS Eagle crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=824%20Naval%20Air%20Squadron%20Swordfish',ops:'Mediterranean carrier and strike operations. Strong modelling route for sun-faded finishes, torpedo or bomb fit, dust, salt and patched fabric.',notes:'HMS Eagle, Mediterranean fade, torpedo/bomb stores, deck handling',map:'taranto'},
 {num:'825 NAS',base:'RAF Manston',theatre:'Home Fleet',impact:90,marks:'Mk.I',codes:'Channel Dash aircraft, individual letters',crew:'Operation Fuller crews',pilot:'Lt Cdr Eugene Esmonde VC DSO',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Fairey%20Swordfish%20Cockpit.jpg?width=900',photoLink:'https://navywings.org.uk/portfolio/channel-dash-unsurpassed-gallantry/',ops:'Channel Dash unit. Six Swordfish from RAF Manston attacked Scharnhorst, Gneisenau and Prinz Eugen in February 1942. This is a harsh winter, low-level torpedo subject with extreme bravery and heavy weathering.',notes:'Operation Fuller, Manston winter finish, torpedo load, Esmonde crew story',map:'manston'},
 {num:'836 NAS',base:'MAC ships / North Atlantic',theatre:'Atlantic',impact:76,marks:'Mk.II / Mk.III',codes:'MAC ship letters; ASV aerials',crew:'Merchant Aircraft Carrier crews',pilot:'MAC ship ASW crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1138.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=836%20Naval%20Air%20Squadron%20Swordfish',ops:'One of the best Swordfish modelling subjects for late-war convoy escort. Use ASV aerials, rockets/depth charges, salt streaking, dull finishes and deck grime.',notes:'MAC ship ASW, ASV aerials, depth charges, salt streaking',map:'atlantic'},
 {num:'838 NAS',base:'HMS Formidable / Indian Ocean',theatre:'Training / Arctic',impact:64,marks:'Mk.II',codes:'Indian Ocean fleet codes',crew:'Indian Ocean crews',pilot:'Eastern Fleet crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=838%20Naval%20Air%20Squadron%20Swordfish',ops:'Eastern Fleet Swordfish route. Use tropical fading, shipboard grime and theatre-specific stores rather than the better-known Atlantic/Taranto look.',notes:'Indian Ocean, tropical fading, fleet carrier work, worn fabric',map:'fareast'},
 {num:'840 NAS',base:'Training and second-line FAA bases',theatre:'Training / Arctic',impact:50,marks:'Mk.II / Mk.III',codes:'training codes and late-war finishes',crew:'Training and conversion crews',pilot:'Operational training crews',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Fairey%20Swordfish%20Cockpit.jpg?width=900',photoLink:'https://www.iwm.org.uk/collections/search?query=840%20Naval%20Air%20Squadron%20Swordfish',ops:'Useful for training, conversion and second-line Swordfish subjects. Allows less-common markings, weathered trainers and late-war equipment fits.',notes:'training aircraft, late-war finishes, conversion units, rigging practice',map:'homefleet'}
];
const timeline=[
 ['1936','Swordfish enters Fleet Air Arm service; its biplane structure already looks dated, but the low-speed carrier handling becomes its strength.'],
 ['1939','War begins with reconnaissance, convoy escort, torpedo training and carrier patrols from Ark Royal, Courageous and Glorious.'],
 ['1940','Taranto proves the value of slow night torpedo attack. Modelling notes: black distemper undersides, torpedo crutches and heavily handled fabric.'],
 ['1941','Ark Royal Swordfish strike Bismarck in severe weather. Atlantic subjects should show salt, wet fabric and deck-scuffed finish.'],
 ['1942','825 NAS attacks during the Channel Dash. Winter Manston Swordfish are grim, low-level torpedo aircraft rather than clean display machines.'],
 ['1943–45','Escort carrier, MAC ship, Arctic convoy and rocket-equipped Mk.II/Mk.III operations dominate late-war Swordfish modelling.']
];
const survivors=[
 {serial:'W5856',status:'Flying',where:'Navy Wings / Yeovilton',img:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900',desc:'Airworthy Swordfish Mk.I with Navy Wings. Best reference for overall sit, exposed cockpit arrangement, wing fold details, rigging geometry and live Pegasus staining.',url:'https://navywings.org.uk/portfolio/fairey-swordfish-w5856/'},
 {serial:'LS326',status:'Flying',where:'Navy Wings / historic flight',img:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900',desc:'Airworthy Swordfish Mk.II. Useful for rigging, Bristol Pegasus exhaust staining, fabric sag, stance and crew positions.',url:'https://navywings.org.uk/portfolio/fairey-swordfish-ls326/'},
 {serial:'HS618',status:'Static',where:'Fleet Air Arm Museum',img:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1138.jpg?width=900',desc:'Fleet Air Arm Museum aircraft, useful for close-up modelling checks around the Pegasus engine, cowling, rigging runs, torpedo gear and museum-preserved finish.',url:'https://www.nmrn.org.uk/visit-us/fleet-air-arm-museum'},
 {serial:'NS122',status:'Static',where:'Canada Aviation and Space Museum',img:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1138.jpg?width=900',desc:'Canadian preserved Swordfish II reference. Useful for late-war/Canadian service context and general airframe detail checks.',url:'https://ingenium.ca/aviation/en/collection-highlight/fairey-swordfish-ii/'}
];
const books=[
 {title:'Warpaint Series No.12: Fairey Swordfish',desc:'Best modelling-first reference route: variants, drawings, colour profiles and squadron schemes.',url:'https://www.amazon.co.uk/Warpaint-Series-No-12-Fairey-Swordfish/dp/B004QF5PB4',use:['colour schemes','variant checks','markings']},
 {title:'Swordfish — Historic Military Aircraft Series',desc:'Modern aircraft history with useful operational context and photographs for modellers.',url:'https://www.amazon.co.uk/Swordfish-Historic-Military-Aircraft-Series/dp/1802824812',use:['general history','photo reference','operations']},
 {title:'Fleet Air Arm Legends: Fairey Swordfish',desc:'FAA-focused reference for service use, carrier operations and aircraft context.',url:'https://www.amazon.co.uk/Fleet-Air-Arm-Legends-Swordfish/dp/1911658492',use:['FAA context','carrier operations','schemes']},
 {title:'Luck of the Devil: Flying Swordfish in WWII',desc:'Robert le Page memoir; useful for crew experience, escort carrier conditions and lived operational detail.',url:'https://www.amazon.co.uk/Luck-Devil-Flying-Swordfish-WWII-ebook/dp/B008O8HMJM',use:['crew stories','weathering context','escort carriers']}
];
const build={
 kits:[
  {title:'Tamiya Fairey Swordfish Mk.I 1:48 — 61068',rating:'★★★★★',desc:'Benchmark Swordfish kit. Excellent fit, surface texture, cockpit visibility and biplane presence. Best choice if you want a serious Swordfish build with rigging and torpedo detail.',url:'https://www.tamiya.com/english/products/61068/index.html',button:'Open Tamiya Mk.I kit',tips:['Best overall large-scale choice','Add PE bracing wires or elastic rigging','Ideal for Ark Royal/Bismarck subjects']},
  {title:'Tamiya Fairey Swordfish Mk.II 1:48 — 61099',rating:'★★★★☆',desc:'Strong late-war Mk.II route with rocket and wheel fit options. Better for Arctic, ASW and escort-carrier subjects than early Taranto aircraft.',url:'https://www.tamiya.com/english/products/61099/index.html',button:'Open Tamiya Mk.II kit',tips:['Late-war rocket/ASW subjects','Good for Arctic convoy finish','Use with Eduard Mk.II sets']},
  {title:'Airfix Fairey Swordfish Mk.I 1:72 — A04053B',rating:'★★★★☆',desc:'Good 1:72 choice for a compact Swordfish. Less forgiving than a monoplane because rigging alignment matters, but excellent for carrier deck dioramas.',url:'https://uk.airfix.com/products/fairey-swordfish-mki-a04053b',button:'Open Airfix Mk.I kit',tips:['Best smaller-scale route','Good Channel Dash/Taranto subject','Rigging planning is essential']},
  {title:'Trumpeter Fairey Swordfish 1:32',rating:'★★★☆☆',desc:'Impressive large display canvas. Check references carefully and budget for extra cockpit, rigging and engine detail; rewarding but not the safest beginner option.',url:'https://www.scalemates.com/kits/trumpeter-03207-fairey-swordfish-mk-i--102803',button:'Open Trumpeter kit reference',tips:['Huge display presence','Needs more checking','Best for advanced builders']}
 ],
 aftermarket:[
  {title:'Eduard Swordfish Mk.I 1:48 PE — FE212',rating:'★★★★★',desc:'Colour photo-etch for Tamiya Mk.I. Useful for cockpit, panel and visible crew station detail.',url:'https://www.eduard.com/Eduard/Photo-etched-parts/Photo-etched-set/Aircraft/1-48/Swordfish-Mk-I-1-48.html',button:'Open Eduard FE212 set',tips:['Cockpit detail','Instrument panel','Best-value visible upgrade']},
  {title:'Tamiya Fairey Swordfish Photo-Etched Bracing Wire Set — 61069',rating:'★★★★★',desc:'Specific bracing wire set for Tamiya Swordfish. Gives a cleaner scale look than over-thick thread if handled carefully.',url:'https://www.wonderlandmodels.com/tamiya-148-fairey-swordfish-etched-parts/',button:'Open Tamiya PE bracing wire set',tips:['Aircraft-specific rigging','Cleaner than heavy thread','Plan before painting']},
  {title:'Eduard Swordfish Mk.II 1:48 PE — FE901',rating:'★★★★☆',desc:'Correct late-war Mk.II PE route for Tamiya. Use for rocket/ASW Swordfish and Arctic convoy subjects.',url:'https://www.eduard.com/eduard/photo-etched-parts/photo-etched-set/aircraft/1-48/swordfish-mk-ii-1-48.html',button:'Open Eduard FE901 set',tips:['Mk.II detail','Late-war fit','Good with rocket aircraft']},
  {title:'Eduard Swordfish Mk.II Masks — EX595',rating:'★★★★☆',desc:'Specific mask route for Tamiya Mk.II. Useful for windscreen, wheels and cleaner paint demarcations.',url:'https://www.eduard.com/eduard/masks/aircraft/1-48/swordfish-mk-ii-1-48-1.html',button:'Open Eduard EX595 masks',tips:['Canopy/windscreen masks','Wheel masking','Saves time on small panes']},
  {title:'USCHI elastic rigging thread',rating:'★★★★☆',desc:'Good flexible rigging option if you prefer elastic line over PE wires. Keep tension subtle and avoid over-scale cable thickness.',url:'https://www.uschivdr.com/products-in-detail/rig-that-thing/',button:'Open USCHI rigging thread',tips:['Elastic rigging','Works for biplanes','Drill holes before paint']}
 ],
 weathering:[
  {title:'Carrier deck and salt wear',rating:'Technique',desc:'Start with a satin FAA camouflage finish, then add pale salt fading across upper wing ribs, leading edges and the fuselage spine. Use thin grey-beige filters rather than harsh silver chipping because much of the aircraft is fabric.',url:'https://www.youtube.com/watch?v=tFVRH27DSEk',button:'Open salt weathering video',tips:['Mist lightened base colour through panels','Add deck scuffs around crew steps','Use restrained chipping on metal cowling only']},
  {title:'Fabric rib shading and doped finish',rating:'Technique',desc:'Avoid heavy black panel-line washes. Shade either side of ribs with a very thin smoke/grey mix, then drybrush or mist the rib tops very lightly. Fabric should look slightly uneven, not like metal plate.',url:'https://www.youtube.com/watch?v=iqGzI6Kk9GU',button:'Open oil-dot fading video',tips:['Use oils for subtle tonal variation','Keep ribs soft','Matt-satin varnish works better than dead flat']},
  {title:'Pegasus radial engine grime',rating:'Technique',desc:'Build brown-black exhaust staining from the collector ring backwards. Add oily dirt below the nose, around cowl panels and along the lower fuselage. The Swordfish should look mechanically busy around the front end.',url:'https://www.youtube.com/watch?v=C-glDg9o5xk',button:'Open aircraft weathering video',tips:['Brown-black mix, not pure black','Add oil seepage under cowling','Keep upper wing contamination asymmetric']},
  {title:'Rigging and final handling',rating:'Technique',desc:'Rig after main painting but before the most fragile aerials and stores. Work from centre section outwards, line by line. On 1:48 builds, slight tension is enough; over-tight rigging can pull struts out of alignment.',url:'https://www.youtube.com/watch?v=n6X6kCioiXQ',button:'Open biplane rigging video',tips:['Pre-drill rigging holes','Use a jig for wing alignment','Touch in holes after tensioning']}
 ],
 sequence:[
  {title:'1. Cockpit and crew stations',rating:'Build stage',desc:'The Swordfish has three exposed crew positions. Paint the cockpit early, add harnesses, radios, Lewis/Vickers equipment and observer detail before closing the fuselage.',url:'#',button:'Read stage note',tips:['Open cockpits are highly visible','Use dark washes sparingly','Add harness texture']},
  {title:'2. Fuselage, lower wing and tailplane',rating:'Build stage',desc:'Build a straight central structure first. Any twist here will show once the upper wing and rigging go on. Test fit torpedo crutches before paint.',url:'#',button:'Read stage note',tips:['Check alignment from front and rear','Dry-fit struts repeatedly','Plan torpedo/depth charge choice']},
  {title:'3. Upper wing, struts and rigging plan',rating:'Build stage',desc:'Mark rigging holes before final paint. Use the kit instructions and reference photos together; Swordfish rigging is visually dominant and needs symmetry.',url:'https://www.youtube.com/watch?v=n6X6kCioiXQ',button:'Open rigging technique video',tips:['Do not rush this step','Work matched pairs of lines','Avoid over-scale wire']},
  {title:'4. Stores, aerials and final weathering',rating:'Build stage',desc:'Choose one role: torpedo strike, depth-charge ASW, rocket Mk.II/III or training aircraft. Final weathering should match the role and theatre, not generic grey dirt.',url:'https://www.youtube.com/watch?v=tFVRH27DSEk',button:'Open weathering technique video',tips:['Torpedo aircraft: deck wear','Arctic aircraft: salt/ice grime','Mediterranean aircraft: sun fading']}
 ]
};
const media=[
 {kind:'Video',title:'Fairey Swordfish — Fleet Air Arm overview',desc:'Useful overview of why the Swordfish mattered and what roles to model.',thumb:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900',url:'https://www.youtube.com/watch?v=Y7km1F_6eqM',button:'Open Swordfish documentary video'},
 {kind:'Photo',title:'Swordfish flying reference',desc:'Useful for overall stance, rigging silhouette, crew positions and torpedo aircraft proportions.',thumb:'https://commons.wikimedia.org/wiki/Special:FilePath/Fairey%20Swordfish%20Cockpit.jpg?width=900',url:'https://en.wikipedia.org/wiki/Fairey_Swordfish',button:'Open flight reference'},
 {kind:'Photo',title:'Swordfish museum wing and rigging detail',desc:'Good for struts, rigging geometry, folded wing checks and fabric surface appearance.',thumb:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1138.jpg?width=900',url:'https://en.wikipedia.org/wiki/Fairey_Swordfish',button:'Open museum reference'},
 {kind:'Photo',title:'Swordfish torpedo / underside reference',desc:'Use for torpedo trolley, lower fuselage, undercarriage stance and weapon fit context.',thumb:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900',url:'https://www.iwm.org.uk/collections/search?query=Fairey%20Swordfish%20torpedo',button:'Open torpedo photo search'},
 {kind:'Video',title:'Rigging biplane models — beginner workflow',desc:'Technique video for the most important Swordfish modelling challenge: clean, even rigging.',thumb:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1138.jpg?width=900',url:'https://www.youtube.com/watch?v=n6X6kCioiXQ',button:'Open rigging video'},
 {kind:'Video',title:'Salt weathering for faded aircraft finishes',desc:'Technique reference for salt fading, sea exposure and weather-beaten FAA finishes.',thumb:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900',url:'https://www.youtube.com/watch?v=tFVRH27DSEk',button:'Open salt weathering video'},
 {kind:'Video',title:'Oil dot filtering for subtle fabric variation',desc:'Useful for faded doped fabric, shadow-shading and restrained tonal variation.',thumb:'https://commons.wikimedia.org/wiki/Special:FilePath/Fairey%20Swordfish%20Cockpit.jpg?width=900',url:'https://www.youtube.com/watch?v=gyteN0kH8UU',button:'Open oil-dot video'},
 {kind:'Archive',title:'IWM Swordfish archive photographs',desc:'Use for carrier decks, crews, weapons loading, operational weathering and real wartime context.',thumb:'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900',url:'https://www.iwm.org.uk/collections/search?query=Fairey%20Swordfish',button:'Open IWM archive'}
];
let currentFilter='all',currentSort='num';
function showTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+id));if(id==='reference')setTimeout(initMap,80);if(id==='overview')setTimeout(initOverviewMap,80)}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
function safeImg(src){return src||'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Fairey%20Swordfish%20in%20Flight%20TR1139.jpg?width=900'}
function handlePhotoError(img,title,url){
  const box=img.closest('.unit-photo,.media-img-wrap,.overview-img,.map-side-photo-wrap,.survivor-card,.media-card');
  img.remove();
  const fallback=document.createElement('div');
  fallback.className='photo-fallback';
  fallback.innerHTML=`<b>${title}</b><span>Image could not be embedded here.</span><a href="${url}" target="_blank" rel="noopener">Open real photo source</a>`;
  if(box&&box.classList.contains('survivor-card')){box.insertBefore(fallback,box.firstChild)}else if(box){box.appendChild(fallback)}
}
function imgTag(src,alt,title,url){
  return `<img alt="${alt}" src="${safeImg(src)}" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="handlePhotoError(this,'${title}','${url}')">`;
}
function renderOverviewTimeline(){document.getElementById('overviewTimeline').innerHTML=timeline.map(t=>`<div class="tl-item"><div class="tl-year">${t[0]}</div><div class="tl-text">${t[1]}</div></div>`).join('')}
function renderUnits(){let list=units.filter(u=>currentFilter==='all'||u.theatre===currentFilter);list.sort((a,b)=>currentSort==='impact'?b.impact-a.impact:currentSort==='base'?a.base.localeCompare(b.base):String(a.num).localeCompare(String(b.num),undefined,{numeric:true}));document.getElementById('unitCount').textContent=`${list.length} units`;document.getElementById('unitGrid').innerHTML=list.map(u=>`<article class="unit-card" onclick="openUnit('${u.num}')"><div class="unit-photo">${imgTag(u.photo, u.num+' Fairey Swordfish reference photo', 'Swordfish real photo source', 'https://commons.wikimedia.org/wiki/Category:Fairey_Swordfish')}</div><h3>${u.num}</h3><div class="unit-meta">${u.marks} · ${u.base} · ${u.theatre}</div><span class="unit-code">${u.codes}</span><p>${u.ops}</p><div class="tag-row">${u.notes.split(',').map(n=>`<span class="tag">${n.trim()}</span>`).join('')}</div></article>`).join('')}
function openUnit(num){const u=units.find(x=>x.num===num);const box=document.getElementById('unitDetail');box.innerHTML=`<h3>${u.num}</h3><div class="unit-meta">${u.crew} · ${u.pilot}</div><p style="color:var(--muted);line-height:1.65">${u.ops}</p><div class="detail-grid"><div class="detail-cell"><b>Base/carrier</b>${u.base}</div><div class="detail-cell"><b>Theatre</b>${u.theatre}</div><div class="detail-cell"><b>Aircraft</b>${u.marks}</div><div class="detail-cell"><b>Codes/markings</b>${u.codes}</div></div><p><strong style="color:var(--gold)">Modelling hook:</strong> ${u.notes}</p><a class="btn" href="${u.photoLink}" target="_blank" rel="noopener">Open pilot / squadron photo reference</a>`;box.classList.add('open');box.scrollIntoView({behavior:'smooth',block:'nearest'})}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('on'));b.classList.add('on');currentFilter=b.dataset.filter;renderUnits()}));
document.querySelectorAll('[data-sort]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-sort]').forEach(x=>x.classList.remove('on'));b.classList.add('on');currentSort=b.dataset.sort;renderUnits()}));
let overviewMap,map;
const swordfishPlaces=[
 {id:'arkroyal',title:'HMS Ark Royal / Gibraltar',lat:36.14,lng:-5.35,desc:'Ark Royal Swordfish operations: Atlantic and Mediterranean torpedo work, including the Bismarck strike. Model salt, wet fabric, torpedo handling and carrier deck wear.',units:['818 NAS','820 NAS'],img:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900'},
 {id:'taranto',title:'Taranto / HMS Illustrious',lat:40.47,lng:17.24,desc:'Taranto raid subjects: night torpedo attack, black distemper undersides, early-war FAA shadow shading and weathered carrier finishes.',units:['810 NAS','815 NAS'],img:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900'},
 {id:'manston',title:'RAF Manston / Channel Dash',lat:51.34,lng:1.35,desc:'Operation Fuller / Channel Dash: winter Manston Swordfish led by Eugene Esmonde. Low-level torpedo aircraft with harsh weathering and tragic story context.',units:['825 NAS'],img:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900'},
 {id:'atlantic',title:'Atlantic convoy routes',lat:54,lng:-24,desc:'MAC ship and escort carrier anti-submarine operations: depth charges, rocket rails, salt streaking, dull finishes and convoy-worn aircraft.',units:['816 NAS','836 NAS'],img:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900'},
 {id:'arctic',title:'Arctic convoys / North Cape',lat:71,lng:27,desc:'Cold-weather late Swordfish operations: rocket rails, ice, salt, soot, dull markings and battered fabric finish.',units:['819 NAS','836 NAS'],img:'https://commons.wikimedia.org/wiki/Special:FilePath/Bournemouth%20Air%20Festival%202013%20%289628401705%29.jpg?width=900'}
];
function addSwordfishTileLayer(targetMap){return L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:8,attribution:'Map data'}).addTo(targetMap)}
function swordMarkerIcon(kind='full'){return L.divIcon({className:kind==='mini'?'swordship-mini':'swordship',iconSize:kind==='mini'?[12,12]:[18,18],iconAnchor:kind==='mini'?[6,6]:[9,9]})}
function initOverviewMap(){const el=document.getElementById('overview-leaflet-map');if(!el||overviewMap)return;overviewMap=L.map(el,{scrollWheelZoom:false,zoomControl:false,attributionControl:false}).setView([46,-8],2);addSwordfishTileLayer(overviewMap);const bounds=[];swordfishPlaces.forEach((p)=>{bounds.push([p.lat,p.lng]);L.marker([p.lat,p.lng],{icon:swordMarkerIcon('mini'),title:p.title}).addTo(overviewMap).bindTooltip(p.title,{direction:'top'});});overviewMap.fitBounds(bounds,{padding:[18,18]})}
function mapUnitButtons(place){return place.units.map(n=>`<button class="filter-btn map-unit-chip" onclick="showTab('squadrons');openUnit('${n}')">${n}</button>`).join('')}
function updateMapPanel(place){document.getElementById('mapInfo').innerHTML=`<h3 class="section-title">${place.title}</h3><p style="color:var(--muted);line-height:1.6">${place.desc}</p><div class="map-side-photo-wrap">${imgTag(place.img, place.title+' Fairey Swordfish reference photo', 'Swordfish real photo source', 'https://commons.wikimedia.org/wiki/Category:Fairey_Swordfish')}</div><div style="margin-top:.75rem"><div class="unit-meta">Linked squadron cards</div>${mapUnitButtons(place)}</div>`}
function initMap(){if(map)return;map=L.map('leaflet-map',{scrollWheelZoom:false}).setView([46,-8],3);addSwordfishTileLayer(map);const bounds=[];swordfishPlaces.forEach((p,i)=>{bounds.push([p.lat,p.lng]);const marker=L.marker([p.lat,p.lng],{icon:swordMarkerIcon('full'),title:p.title}).addTo(map);marker.bindTooltip(String(i+1),{permanent:true,direction:'center',className:'sword-marker'});marker.on('click',()=>updateMapPanel(p))});map.fitBounds(bounds,{padding:[35,35]});updateMapPanel(swordfishPlaces[0])}
function renderReference(){document.getElementById('refTimeline').innerHTML=timeline.map(t=>`<div style="margin-bottom:.85rem"><div class="tl-year">${t[0]}</div><p style="color:var(--muted);line-height:1.45">${t[1]}</p></div>`).join('');document.getElementById('survivors').innerHTML=survivors.map(s=>`<article class="book-card survivor-card">${imgTag(s.img, s.serial+' Fairey Swordfish reference photo', 'Swordfish real photo source', 'https://commons.wikimedia.org/wiki/Category:Fairey_Swordfish')}<div><h3>${s.serial}</h3><div class="unit-meta">${s.status} · ${s.where}</div><p>${s.desc}</p><a class="btn" href="${s.url}" target="_blank" rel="noopener">Open survivor reference</a></div></article>`).join('');document.getElementById('bookGrid').innerHTML=books.map(b=>`<article class="book-card"><h3>${b.title}</h3><p>${b.desc}</p><ul>${b.use.map(u=>`<li>${u}</li>`).join('')}</ul><a class="btn" href="${b.url}" target="_blank" rel="noopener">Open Amazon book</a></article>`).join('')}
let currentBuild='kits';
function renderBuild(){document.getElementById('buildGrid').innerHTML=build[currentBuild].map(x=>`<article class="build-card"><h3>${x.title}</h3><div class="rating">${x.rating}<span>${currentBuild==='kits'||currentBuild==='aftermarket'?'rating / usefulness':'modelling guide'}</span></div><p>${x.desc}</p><ul>${x.tips.map(t=>`<li>${t}</li>`).join('')}</ul>${x.url==='#'?'<span class="btn">'+x.button+'</span>':`<a class="btn" href="${x.url}" target="_blank" rel="noopener">${x.button}</a>`}</article>`).join('')}
document.querySelectorAll('[data-build]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-build]').forEach(x=>x.classList.remove('on'));b.classList.add('on');currentBuild=b.dataset.build;renderBuild()}));
function renderMedia(){document.getElementById('mediaGrid').innerHTML=media.map(m=>`<article class="media-card"><div class="media-img-wrap">${imgTag(m.thumb, m.title+' Fairey Swordfish reference photo', 'Swordfish real photo source', 'https://commons.wikimedia.org/wiki/Category:Fairey_Swordfish')}</div><span class="video-badge">${m.kind}</span><h3>${m.title}</h3><p>${m.desc}</p><a class="btn" href="${m.url}" target="_blank" rel="noopener">${m.button}</a></article>`).join('')}

const buildProfiles={
 taranto:{title:'Taranto raid Swordfish',summary:'Best for a dramatic early-war Fleet Air Arm subject: night operation, torpedo fit, HMS Illustrious context and dark operational wear.',scheme:'Early FAA camouflage; check shadow-shading and possible night distemper notes.',stores:'18-inch torpedo, carrier deck handling gear.',weathering:'Restrained night-fighter style grime: exhaust, oil, deck scuffs and salt haze.',links:'Use 815 NAS / 819 NAS material, torpedo references and Taranto campaign notes.'},
 bismarck:{title:'Bismarck strike Swordfish',summary:'Ark Royal aircraft with rough Atlantic conditions and the most famous Swordfish torpedo story.',scheme:'Temperate Sea Scheme with wet, salt-streaked fabric and worn carrier-deck contact points.',stores:'Torpedo fit, crew of three, long over-water strike load.',weathering:'Salt streaks, wet deck grime, oil on Pegasus cowling and restrained fabric fading.',links:'Use Ark Royal / 818 and 820 NAS references.'},
 atlantic:{title:'Atlantic convoy Swordfish',summary:'Escort carrier and MAC ship subject focused on anti-submarine patrols rather than headline torpedo attacks.',scheme:'Late-war FAA finish; check ASW role and ship type before choosing markings.',stores:'Depth charges, rockets or patrol stores depending on unit and date.',weathering:'Salt bleaching, dull fabric, exhaust staining and maintenance grime.',links:'Use 816 / 836 NAS convoy references.'},
 arctic:{title:'Arctic convoy Swordfish',summary:'Cold-weather Swordfish with harsh conditions, dull finishes and dramatic convoy context.',scheme:'Temperate Sea Scheme with cold-weather grime and poor-light contrast.',stores:'Rockets and ASW stores are plausible for late convoy subjects.',weathering:'Frost, salt, soot, chipped access points and restrained grime around service areas.',links:'Use North Cape / Arctic convoy references.'},
 training:{title:'Training or late-war Swordfish',summary:'Good route for a different finish: training markings, rocket trials, radar fits or worn second-line aircraft.',scheme:'Check yellow training areas, radar fit and late-war markings carefully.',stores:'May vary from clean trainer to rocket-equipped Mk.II or radar Mk.III.',weathering:'Less combat damage, more training wear, mud, oil and repeated handling.',links:'Use museum and restoration references for details.'}
};
function renderBuildProfile(key){const defaultBtn=document.querySelector('[data-profile].on')||document.querySelector('[data-profile]');key=key||(defaultBtn?defaultBtn.dataset.profile:Object.keys(buildProfiles)[0]);const p=buildProfiles[key]||buildProfiles[Object.keys(buildProfiles)[0]];const el=document.getElementById('buildProfile');if(!el||!p)return;el.innerHTML=`<h3>${p.title}</h3><p>${p.summary}</p><div class="profile-grid"><div class="profile-cell"><b>Scheme</b>${p.scheme}</div><div class="profile-cell"><b>Fit</b>${p.stores}</div><div class="profile-cell"><b>Weathering</b>${p.weathering}</div><div class="profile-cell"><b>References</b>${p.links}</div></div>`}
document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-profile]').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderBuildProfile(b.dataset.profile)}));
const wizardResults={
 easy:'Recommended: Tamiya 1:48 Swordfish Mk.I/Mk.II where available. Best balance of fit, detail and support. Add masks and rigging material before extra resin.',
 detail:'Recommended: Tamiya 1:48 with photo-etch rigging, mask set, resin/3D cockpit detail and careful torpedo references.',
 large:'Recommended: Trumpeter 1:32 Swordfish if you want a display centrepiece. Expect more time on rigging, fabric texture and interior visibility.',
 rigging:'Recommended: choose the kit you trust most for wing alignment, then invest in a rigging system: PE bracing wires, elastic thread or monofilament.'
};
function renderWizard(key='easy'){const el=document.getElementById('kitWizardResult');if(el)el.textContent=wizardResults[key]}
document.querySelectorAll('[data-wizard]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-wizard]').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderWizard(b.dataset.wizard)}));
const variantInfo={
 mk1:'Mk.I: early torpedo and reconnaissance aircraft. Focus on torpedo crutches, early FAA camouflage, shadow-shading and carrier-deck wear.',
 mk2:'Mk.II: strengthened lower wing and rocket-capable subjects. Check rocket rails, ASW stores and late-war FAA finish before painting.',
 mk3:'Mk.III: radar-equipped ASW aircraft. Focus on radar fit, aerials, operator position and late-war convoy patrol weathering.'
};
function renderVariant(key='mk1'){const el=document.getElementById('variantResult');if(el)el.textContent=variantInfo[key]}
document.querySelectorAll('[data-variant]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-variant]').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderVariant(b.dataset.variant)}));

renderBuildProfile();renderWizard();renderVariant();
renderOverviewTimeline();renderUnits();renderReference();renderBuild();renderMedia();setTimeout(initOverviewMap,80);
